### ISSUE TITLE
You are using non-existent method Serial.printf. Please remove these function calls as they break the whole library.

### ISSUE THREAD

**Issue by macaquedev** [pablo-sampaio/easy_mfrc522#1]
I've got a fix on my computer, please give me access rights and I will commit it.

**Comment by pablo-sampaio** [comment]
Hi macaquedev. Thank you for reporting this issue. 

It seems that his error appears in Windows versions of Arduino IDE (versions 1.8.15 and 1.8.19) and on the Web version. 
But it worked fine in Ubuntu here (Arduino IDE version 1.8.15).

Since you have developed a solution, I ask you to do the following, please:
- fork the project
- commit/push to your forked repository
- click on "pull request" on your repository on github and proceed to create a "pull request"

Then I can review and merge the code in the main repository.

Pablo A. Sampaio

**Comment by pablo-sampaio** [comment]
Solved in v0.2.2.
